site_name: pinax-waitinglist
pages:
- [index.md, Home]
- [usage.md, Usage]
- [settings.md, Settings]
- [reference.md, Reference]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-waitinglist
site_description: "documentation for pinax-waitinglist, a waiting list app for Django sites"
site_author:  "Pinax Team"
markdown_extensions: [admonition]